config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :events, path: 'eventi'
  resources :menu_items
  resources :breadcrumbs

  devise_for :users

  get 'montessori', to: 'montessori#index'

  get 'comitatomamme', to: 'comitatomamme#index'

  get 'comunicazioni', to: 'comunicazioni#index'

  get 'documenti', to: 'documenti#index'

  get 'servizi', to: 'servizi#index'

  get 'orari', to: 'orari#index'

  get 'scuola', to: 'scuola#index'

  get 'storia', to: 'storia#index'

  resources :tasks do
    resources :pictures
  end

  resources :projects, path: 'progetti' do
    resources :tasks
  end

  root 'home#index'

end

app/models/breadcrumb.rb
class Breadcrumb < ActiveRecord::Base
  belongs_to :menu_item

end

app/models/event.rb
class Event < ActiveRecord::Base

  scope :next_events, -> { where("quando >= ? ", DateTime.now.to_date )}

  geocoded_by :address

  after_validation :geocode, :if => :address_changed?

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base

  scope :by_priority, -> { order("priority asc")}

  attr_accessor :active

  has_one :breadcrumb


  def initialize *args,&block
    super *args,&block
    @active = Date.new(9999,12,31) unless @active
  end

  def to_partial_path
    'application/menu_item'
  end

  def is_active?
    result = false
    if active == Date.new(9999,12,31)
      result = true
    end
    result
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base

  belongs_to :uploadable, polymorphic: true
  mount_uploader :image, ImageUploader

  before_create :default_name

  def default_name
    self.name ||= File.basename(image.filename, '.*').titleize if image
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  friendly_id :titolo, use: [:slugged, :finders]

  scope :by_type, -> (tipo) { where tipo: tipo}
  scope :most_recent, -> (limit) { order("pubblicato desc").limit(limit) }

end

app/models/project.rb
class Project < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  has_many :tasks, :dependent => :destroy
  accepts_nested_attributes_for :tasks, allow_destroy: true

  # Rende la lista di tutte le attività in ordine cronologico collegate al progetto
  def ordered_tasks
    tasks.sort_by &:started_at
  end

  def all_pictures
    pictures = []
    tasks.each do |task|
      task.pictures.each do |picture|
        pictures << picture
      end
    end
    pictures
  end

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project
  has_many :pictures, as: :uploadable
  accepts_nested_attributes_for :pictures, allow_destroy: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/breadcrumbs_controller.rb
class BreadcrumbsController < ApplicationController
  before_action :set_breadcrumb, only: [:show, :edit, :update, :destroy]

  # GET /breadcrumbs
  # GET /breadcrumbs.json
  def index
    @breadcrumbs = Breadcrumb.all
  end

  # GET /breadcrumbs/1
  # GET /breadcrumbs/1.json
  def show
  end

  # GET /breadcrumbs/new
  def new
    @breadcrumb = Breadcrumb.new
  end

  # GET /breadcrumbs/1/edit
  def edit
  end

  # POST /breadcrumbs
  # POST /breadcrumbs.json
  def create
    @breadcrumb = Breadcrumb.new(breadcrumb_params)

    respond_to do |format|
      if @breadcrumb.save
        format.html { redirect_to @breadcrumb, notice: 'Breadcrumb was successfully created.' }
        format.json { render :show, status: :created, location: @breadcrumb }
      else
        format.html { render :new }
        format.json { render json: @breadcrumb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breadcrumbs/1
  # PATCH/PUT /breadcrumbs/1.json
  def update
    respond_to do |format|
      if @breadcrumb.update(breadcrumb_params)
        format.html { redirect_to @breadcrumb, notice: 'Breadcrumb was successfully updated.' }
        format.json { render :show, status: :ok, location: @breadcrumb }
      else
        format.html { render :edit }
        format.json { render json: @breadcrumb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breadcrumbs/1
  # DELETE /breadcrumbs/1.json
  def destroy
    @breadcrumb.destroy
    respond_to do |format|
      format.html { redirect_to breadcrumbs_url, notice: 'Breadcrumb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breadcrumb
      @breadcrumb = Breadcrumb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def breadcrumb_params
      params.require(:breadcrumb).permit(:title, :menu_item_id, :visible, :active)
    end
end

app/helpers/breadcrumbs_helper.rb
module BreadcrumbsHelper
end

app/helpers/documenti_helper.rb
module DocumentiHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/montessori_helper.rb
module MontessoriHelper
end

app/helpers/orari_helper.rb
module OrariHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def class_for element
    if @post.tipo == 'comitatomamme'
      "#{element} pink"
    else
      element
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  # Per presentare la data di inizio progetto
  # una semplice formattazione
  def presenta_data_inizio data
    format_date data
  end

  # Per presentare la data di conclusione di un progetto
  # Il metodo controlla l'identità delle data di inizio e fine del progetto
  # L'uguaglianza di data inizio e data fine significa che il progetto è ancora in corso
  # in tal caso viene mostrato all'utente il testo "in corso"
  def presenta_data_conclusione progetto
    if progetto.started_at == progetto.finished_at
      "in corso"
    else
      format_date progetto.finished_at
    end
  end


  # Imposta classe adeguata per l'attività
  # solo una ogni 4 deve avere la classe 'first'
  def class_for_activity index
    if index%4 == 0
      "portfolio dt-sc-one-fourth column first"
    else
      "portfolio dt-sc-one-fourth column"
    end
  end

  # Rivela se è stata richiesta una nuova immagine da caricare
  # vuole impedire di poter caricare una nuova immagine
  # al posto di una vecchia
  def new_image object
    object.created_at == nil
  end

  private

  def format_date data
    data.strftime("%d/%m/%Y")
  end

end

app/helpers/scuola_helper.rb
module ScuolaHelper
end

app/helpers/servizi_helper.rb
module ServiziHelper
end

app/helpers/storia_helper.rb
module StoriaHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/breadcrumbs/_form.html.erb
<%= form_for(@breadcrumb) do |f| %>
  <% if @breadcrumb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@breadcrumb.errors.count, "error") %> prohibited this breadcrumb from being saved:</h2>

      <ul>
      <% @breadcrumb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :menu_item_id %><br>
    <%= f.select :menu_item_id, MenuItem.all.collect { |p| [ p.label, p.id ] }%>
  </div>
  <div class="field">
    <%= f.label :visible %><br>
    <%= f.text_field :visible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breadcrumbs/edit.html.erb
<h1>Editing Breadcrumb</h1>

<%= render 'form' %>

<%= link_to 'Show', @breadcrumb %> |
<%= link_to 'Back', breadcrumbs_path %>

app/views/breadcrumbs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Breadcrumbs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Menu item</th>
      <th>Visible</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breadcrumbs.each do |breadcrumb| %>
      <tr>
        <td><%= breadcrumb.title %></td>
        <td><%= breadcrumb.menu_item_id %></td>
        <td><%= breadcrumb.visible %></td>
        <td><%= link_to 'Show', breadcrumb %></td>
        <td><%= link_to 'Edit', edit_breadcrumb_path(breadcrumb) %></td>
        <td><%= link_to 'Destroy', breadcrumb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breadcrumb', new_breadcrumb_path %>

app/views/breadcrumbs/new.html.erb
<h1>New Breadcrumb</h1>

<%= render 'form' %>

<%= link_to 'Back', breadcrumbs_path %>

app/views/breadcrumbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @breadcrumb.title %>
</p>

<p>
  <strong>Menu item:</strong>
  <%= @breadcrumb.menu_item_id %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @breadcrumb.visible %>
</p>

<%= link_to 'Edit', edit_breadcrumb_path(@breadcrumb) %> |
<%= link_to 'Back', breadcrumbs_path %>