config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :events, path: 'eventi'
  resources :menu_items
  resources :breadcrumbs

  devise_for :users

  get 'montessori', to: 'montessori#index'

  get 'comitatomamme', to: 'comitatomamme#index'

  get 'comunicazioni', to: 'comunicazioni#index'

  get 'documenti', to: 'documenti#index'

  get 'servizi', to: 'servizi#index'

  get 'orari', to: 'orari#index'

  get 'scuola', to: 'scuola#index'

  get 'storia', to: 'storia#index'

  resources :tasks do
    resources :pictures
  end

  resources :projects, path: 'progetti' do
    resources :tasks
  end

  root 'home#index'

end

app/models/breadcrumb.rb
class Breadcrumb < ActiveRecord::Base
  belongs_to :menu_item

end

app/models/event.rb
class Event < ActiveRecord::Base

  scope :next_events, -> { where("quando >= ? ", DateTime.now.to_date )}

  geocoded_by :address

  after_validation :geocode, :if => :address_changed?

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base

  scope :by_priority, -> { order("priority asc")}

  attr_accessor :active

  has_one :breadcrumb


  def initialize *args,&block
    super *args,&block
    @active = Date.new(9999,12,31) unless @active
  end

  def to_partial_path
    'application/menu_item'
  end

  def is_active?
    result = false
    if active == Date.new(9999,12,31)
      result = true
    end
    result
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base

  belongs_to :uploadable, polymorphic: true
  mount_uploader :image, ImageUploader

  before_create :default_name

  def default_name
    self.name ||= File.basename(image.filename, '.*').titleize if image
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  friendly_id :titolo, use: [:slugged, :finders]

  scope :by_type, -> (tipo) { where tipo: tipo}
  scope :most_recent, -> (limit) { order("pubblicato desc").limit(limit) }

end

app/models/project.rb
class Project < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  has_many :tasks, :dependent => :destroy
  accepts_nested_attributes_for :tasks, allow_destroy: true

  # Rende la lista di tutte le attività in ordine cronologico collegate al progetto
  def ordered_tasks
    tasks.sort_by &:started_at
  end

  def all_pictures
    pictures = []
    tasks.each do |task|
      task.pictures.each do |picture|
        pictures << picture
      end
    end
    pictures
  end

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project
  has_many :pictures, as: :uploadable
  accepts_nested_attributes_for :pictures, allow_destroy: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :get_uploadable
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = @uploadable.pictures
    #@pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = @uploadable.pictures.new
    #@picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = @uploadable.pictures.new(picture_params)
    #@picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def load_uploadable
      resource, id = request.path.split('/')[1, 2]
      @uploadable = resource.singularize.classify.constantize.find(id)
    end

    def get_uploadable
      @uploadable = params[:uploadable].classify.constantize.find(uplodable_id)
    end

    def uploadable_id
      params[(params[:uploadable_id].singularize + "_id").to_sym]
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:name, :description, :image, :sensible, :uploadable_id, :uploadable_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title page_title
    content_for(:title) { page_title }
  end

  def current_page name
    'current_page_item' if controller.controller_name == name
  end

  def current_breadcrumb name
    true if controller.controller_name == name
  end

  def millisec_to_formated_date millisec
    Date.strptime((millisec.to_f / 1000).to_s, '%s').strftime("%d/%m/%Y")
  end

  def event_date event
    millisec_to_formated_date event.quando
  end

  def event_time event
    "#{event.ora.hour}:#{event.ora.min}"
  end

end

app/helpers/documenti_helper.rb
module DocumentiHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/montessori_helper.rb
module MontessoriHelper
end

app/helpers/orari_helper.rb
module OrariHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def class_for element
    if @post.tipo == 'comitatomamme'
      "#{element} pink"
    else
      element
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  # Per presentare la data di inizio progetto
  # una semplice formattazione
  def presenta_data_inizio data
    format_date data
  end

  # Per presentare la data di conclusione di un progetto
  # Il metodo controlla l'identità delle data di inizio e fine del progetto
  # L'uguaglianza di data inizio e data fine significa che il progetto è ancora in corso
  # in tal caso viene mostrato all'utente il testo "in corso"
  def presenta_data_conclusione progetto
    if progetto.started_at == progetto.finished_at
      "in corso"
    else
      format_date progetto.finished_at
    end
  end


  # Imposta classe adeguata per l'attività
  # solo una ogni 4 deve avere la classe 'first'
  def class_for_activity index
    if index%4 == 0
      "portfolio dt-sc-one-fourth column first"
    else
      "portfolio dt-sc-one-fourth column"
    end
  end

  # Rivela se è stata richiesta una nuova immagine da caricare
  # vuole impedire di poter caricare una nuova immagine
  # al posto di una vecchia
  def new_image object
    object.created_at == nil
  end

  private

  def format_date data
    data.strftime("%d/%m/%Y")
  end

end

app/helpers/scuola_helper.rb
module ScuolaHelper
end

app/helpers/servizi_helper.rb
module ServiziHelper
end

app/helpers/storia_helper.rb
module StoriaHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/pictures/_form.html.erb
<%= form_for @picture, :html => {:multipart => :true} do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.name %></td>
        <td><%= picture.description %></td>
        <td><%= picture.image %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @picture.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @picture.image %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>